directories:
  output: dist
  buildResources: build
appId: zendvn.cts-trading-helper
asar: false
publish:
  - provider: generic
    url: 'https://github.com/Thienhuynh95/cts-trading-helper.git'
win:
  target:
    - nsis
  artifactName: 'CTS-setup.${ext}'
  icon: public/themes/electron/assets/app-icon/win/app.ico
  verifyUpdateCodeSignature: false
mac:
  target:
    - dmg
  icon: public/themes/electron/assets/app-icon/mac/mac.icns
linux:
  target:
    - AppImage
electronVersion: 2.0.6
