<?php 
    $theme_url = ZCMS_THEME_URL . '/sbackend';
?>
<?php echo $zHtml->getDoctype();?>
<html>

<head>
    <?php echo $zHtml->outputHeader();?>
</head>

<body>
	<div id="pre-load">
        <div class="sk-spinner sk-spinner-three-bounce">
            <div class="sk-bounce1"></div>
            <div class="sk-bounce2"></div>
            <div class="sk-bounce3"></div>
        </div>
    </div>
    <div id="wrapper">
        <!-- START - LEFT SIDEBAR -->
        <?php include_once 'includes/left_sidebar.php';?>
        <!-- END - LEFT SIDEBAR -->
        
        <div id="page-wrapper" class="gray-bg">
        	
            <!-- START - HEADER -->
            <?php require_once 'includes/header.php';?>
            <!-- END - HEADER -->
            
            <!-- START - HEADER TITLE-->
            <?php 
                if($zHtml->getHeaderState() == true) require_once 'includes/header_title.php';
            ?>
            <!-- END - HEADER TITLE-->
            
            <div class="wrapper wrapper-content animated fadeInRight">
            	<?php echo $this->getContent(); ?>
        	</div>

            <!-- START - FOOTER -->
            <?php include_once 'includes/footer.php';?>
            <!-- START - FOOTER -->        
        </div>
        
        <!-- START - SMALL CHAT -->
        <?php //include_once 'includes/small_chat.php';?>
        <!-- START - SMALL CHAT -->
        
        <!-- START - RIGHT SIDEBAR -->
        <?php include_once 'includes/right_sidebar.php';?>
        <!-- START - RIGHT SIDEBAR -->
    </div>
    
    <?php echo $zHtml->outputFooter(); ?>
</body>
</html>
